import Image from 'next/image';
import Link from 'next/link';
import React from 'react';

import shoes from '../../../public/ballet.png';

export default function Footer() {
  return (
    <footer className="py-6 font-bdsans font-black">
      <div className="container py-8 mx-auto">
        <Image src={shoes} className="w-28 m-auto" alt="ballet shoes" />
        <div className="flex flex-col items-center text-center text-xs gap-2">
          <div>This is a DEMO</div>
          <div>All content is generated by AI</div>
          <div>designed and developed + [createdbydwe]</div>
        </div>

        <hr className="my-4 border-bbrown/20 md:my-10 " />

        <div className="flex flex-col items-center text-center text-xs sm:flex-row sm:justify-between">
          {/* <div>designed and developed + [createdbydwe]</div> */}
          <Link
            href="https://www.createdbydwe.tech"
            target="_blank"
            className="transition-colors duration-300 hover:text-[#b95f80]"
          >
            www.createdbydwe.tech
          </Link>
        </div>
      </div>
    </footer>
  );
}
